# Generated by Django 5.1.7 on 2025-03-13 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyjob',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.story'),
        ),
    ]
