# Generated by Django 5.1.7 on 2025-03-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_storyjob_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
