# Generated by Django 5.1.7 on 2025-03-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_story_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
