# Generated by Django 5.1.7 on 2025-03-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_storyjob_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='audio_data',
            new_name='audios',
        ),
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
        migrations.AddField(
            model_name='story',
            name='text_sections',
            field=models.TextField(blank=True, null=True),
        ),
    ]
