# Generated by Django 5.1.7 on 2025-03-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_audio_data_story_audios_remove_story_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyjob',
            name='description',
        ),
        migrations.RemoveField(
            model_name='storyjob',
            name='title',
        ),
    ]
