# Generated by Django 5.1.7 on 2025-03-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_storyjob_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('generating_story', 'Generating Story'), ('generating_audio', 'Generating Audio'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
