# Generated by Django 5.1.7 on 2025-04-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_story_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='characters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='audios',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='text_sections',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
