# Generated by Django 5.1.7 on 2025-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_storycharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycharacter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
