# Generated by Django 5.1.7 on 2025-04-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_storycharacter_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storycharacter',
            name='image_url',
        ),
        migrations.AddField(
            model_name='storycharacter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_characters/'),
        ),
    ]
