# Generated by Django 5.1.7 on 2025-04-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_storytheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyjob',
            name='user',
        ),
    ]
