# Generated by Django 5.1.7 on 2025-04-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_storyjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storyjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('generating_story', 'Generating Story'), ('generating_image', 'Generating Image'), ('generating_audio', 'Generating Audio'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
