# Generated by Django 5.1.7 on 2025-04-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_story_images_alter_storyjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
